---
title: "Review Analysis"
author: "Kaiyan"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    df_print: paged
---
# 1.

```{r}
data <- read.csv("../Data/yelp_review_filtered_breakfast.csv")
head(data)
```


```{r}
library(stringr)
library(tidytext)
library(tidyr)
library(dplyr)
library(topicmodels)
library(ggplot2)
library(stopwords)
library(readr)
library(tidyverse)
```




```{r}
#stopwords
my_stopwords <- strsplit(read_file("gist_stopwords.txt"),",")[[1]]
stop_words_all <- rbind(stop_words,data.frame("word"=my_stopwords,"lexicon"=rep("user",length(my_stopwords))))

# split into words
data_word <- data %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words_all)
```

# doc: take each review as a document

## 1 star
```{r}
# find document-word counts
star1_dtm <- data_word[data_word$stars==1,] %>%
  count(review_id, word, sort = TRUE) %>%
  cast_dtm(review_id, word, n)

star1_lda <- LDA(star1_dtm, k = 3, control = list(seed = 1234))

stars_topics <- tidy(star1_lda, matrix = "beta")

top_terms <- stars_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 30) %>% 
  ungroup() %>%
  arrange(topic, -beta) 

top_terms%>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()+ 
  ggtitle("Topics in 1-star reviews")

```

## 2 stars

```{r}
# find document-word counts
stars2_lda <- data_word[data_word$stars==2,] %>%
  count(review_id, word, sort = TRUE) %>%
  cast_dtm(review_id, word, n) %>%
  LDA(k = 3, control = list(seed = 1234))

stars_topics <- tidy(stars2_lda, matrix = "beta")

top_terms <- stars_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 30) %>% 
  ungroup() %>%
  arrange(topic, -beta) 

top_terms%>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()+ 
  ggtitle("Topics in 2-star reviews")

```


## 3 stars

```{r}
d3s <- data[data$stars=="3",8]
head(d3s[grep("menu",d3s$text),8])

"It's nice to have a decent culinary option in NE, but I hear folks talking about this place like it is the second coming of Christ!\n\nThe duck fries were some of best fries I've ever had.  Get them, won't disappoint. The duck sandwich and pork roll burger were both bland and barely mediocre. Salads were grossly overdressed.   \n\nI'd try it again if I were in the NE."        
```

```{r}
# find document-word counts
stars3_lda <- data_word[data_word$stars==3,] %>%
  count(review_id, word, sort = TRUE) %>%
  cast_dtm(review_id, word, n) %>%
  LDA(k = 3, control = list(seed = 1234))

stars_topics <- tidy(stars3_lda, matrix = "beta")

top_terms <- stars_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 30) %>% 
  ungroup() %>%
  arrange(topic, -beta) 

top_terms%>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()+ 
  ggtitle("Topics in 3-star reviews")

```

## 4 stars

```{r}
# find document-word counts
stars4_lda <- data_word[data_word$stars==4,] %>%
  count(review_id, word, sort = TRUE) %>%
  cast_dtm(review_id, word, n) %>%
  LDA(k = 3, control = list(seed = 1234))

stars_topics <- tidy(stars4_lda, matrix = "beta")

top_terms <- stars_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 30) %>% 
  ungroup() %>%
  arrange(topic, -beta) 

top_terms%>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()+ 
  ggtitle("Topics in 4-star reviews")

```

## 5 stars
```{r}
# find document-word counts
stars5_lda <- data_word[data_word$stars==5,] %>%
  count(review_id, word, sort = TRUE) %>%
  cast_dtm(review_id, word, n) %>%
  LDA(k = 3, control = list(seed = 1234))

stars_topics <- tidy(stars5_lda, matrix = "beta")

top_terms <- stars_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 30) %>% 
  ungroup() %>%
  arrange(topic, -beta) 

top_terms%>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()+ 
  ggtitle("Topics in 5-star reviews")

```






# doc: take each star as a document (5 docs)
```{r}
stars_dtm <- data_word %>%
  count(stars, word, sort = TRUE) %>%
  cast_dtm(stars, word, n)

stars_lda <- LDA(stars_dtm, k = 6, control = list(seed = 1234))

stars_topics <- tidy(stars_lda, matrix = "beta")

top_terms <- stars_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 50) %>% 
  ungroup() %>%
  arrange(topic, -beta)


top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()+ 
  ggtitle("Topics in all the reviews")

```


```{r}
stars_gamma <- tidy(stars_lda, matrix = "gamma")

# add other id cols

stars_gamma[is.na(stars_gamma$document),1] <- rep("no rating",6)

stars_gamma

stars_gamma %>%
  ggplot(aes(factor(topic), gamma)) +
  geom_bar(stat='identity') +
  facet_wrap(~ document) +
  labs(x = "topic", y = expression(gamma))+ 
  ggtitle("Topics distribution in each star-level")

```


## perplexity
Inflection point: n=6
```{r}
n_topics <- c(2,4,5,6,7,8,10,20)

ap_lda_compare <- n_topics %>%
map(LDA, x = stars_dtm, control = list(seed = 1109)) 

perplexity_lda <- c()
for (i in ap_lda_compare) {
  perplexity_lda <- c(perplexity_lda,perplexity(i))
}


df <- data.frame(n_topics = n_topics, perplexity_lda = perplexity_lda)

ggplot(data = df, mapping = aes(x = n_topics, y = perplexity_lda)) + geom_line() + geom_point()

'''
nt <- c(nt,n_topics)
pp <- c(pp,perplexity_lda)

df <- data.frame("n_topics"=nt,"perplexity_lda"=pp)
df
ggplot(data = df, aes(x = n_topics, y = perplexity_lda)) + geom_line() + geom_point()
'''
```



```{r}

```




# doc: take each row as a document (42194 docs)

```{r}
data_word_count <- data_word %>%
  count(review_id, word, sort = TRUE)

review_id_dtm <- data_word_count %>%
  cast_dtm(review_id, word, n)
review_id_dtm
```

## perplexity skip
```{r}
n_topics <- c(5,10,15,20,50,100)

ap_lda_compare <- n_topics %>%
map(LDA, x = review_id_dtm, control = list(seed = 1109)) 

perplexity_lda <- c()
for (i in ap_lda_compare) {
  perplexity_lda <- c(perplexity_lda,perplexity(i))
}


df <- data.frame(n_topics = n_topics, perplexity_lda = perplexity_lda)

ggplot(data = df, mapping = aes(x = n_topics, y = perplexity_lda)) + geom_line() + geom_point()

'''
nt <- c(nt,n_topics)
pp <- c(pp,perplexity_lda)

df <- data.frame("n_topics"=nt,"perplexity_lda"=pp)
df
ggplot(data = df, aes(x = n_topics, y = perplexity_lda)) + geom_line() + geom_point()
'''
```




## lda
```{r}
review_id_lda <- LDA(review_id_dtm, k = 10, control = list(seed = 1234))

review_id_topics <- tidy(review_id_lda, matrix = "beta")

top_terms <- review_id_topics %>%
  group_by(topic) %>%
  slice_max(beta, n = 50) %>% 
  ungroup() %>%
  arrange(topic, -beta)

write.csv(top_terms,"../Data/top_terms.csv")

perplexity(review_id_lda)
```


```{r}
top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()+ 
  ggtitle("Topics in all the reviews")

```


```{r}
review_id_gamma <- tidy(review_id_lda, matrix = "gamma")

# add other id cols
library(reshape2)

review_id_gamma_wide <- review_id_gamma %>%
  dcast(document ~ topic, value.var="gamma")

colnames(review_id_gamma_wide) <- c("review_id",paste("Topic",colnames(review_id_gamma_wide[-1]),sep=""))



yelp_review_add_gamma <- merge(data,review_id_gamma_wide,by="review_id")

write.csv(yelp_review_add_gamma,"../Data/yelp_review_add_gamma.csv")

yelp_review_add_gamma
```



```{r}

review_id_gamma %>%
  ggplot(aes(factor(topic), gamma)) +
  geom_bar(stat='identity') +
  facet_wrap(~ document) +
  labs(x = "topic", y = expression(gamma))+ 
  ggtitle("Topics distribution in each star-level")

```


```{r}
```

